spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: Zhishu_121
    url: jdbc:mysql://47.101.54.182:3306/sell?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
  jackson:
    default-property-inclusion: non_null
server:
  servlet:
    context-path: /sell